version: '3'
services:
  mongo:
    image: mongo:4.0.9-xenial
    volumes:
      - ./mongo:/data/db
    networks:
      - app-network
    ports:
      - "27017:27017"
  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - mongo
    ports:
     - "3333:3333"
    networks:
    - app-network
  postgres:
    volumes:
      - ./postgres:/
    networks:
      - app-network
networks:
  app-network:
    driver: bridge